name: 'Remote Config Release Registration'
description: 'Registering a new release in remote-config'
inputs:
  package-id:
    description: 'provisioning package id in artifacts'
    required: true
  API_TOKEN_GITHUB:
    description: 'github api token with full-repo access'
    required: true

runs:
  using: "composite"
  steps:
    # - name: "Checkout the repository"
    #   uses: actions/checkout@v2

    - name: "Get provisioning package"
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.package-id }}
        path: ./tmp

    - name: Get Timestamp
      id: time
      uses: nanzm/get-time-action@v1.1
      with:
        format: 'YYYY-MM-DD-HH-mm-ss'

    - name: "Bump version and create PR"
      uses: ./.github/actions/create-pr
      with:
          image-tag-name: remote-config-v-${{ github.run_number }}-${{ steps.time.outputs.time }}
          user-email: milad@backbase.com
          user-name: miladbb
          organization-name: miladbb
          repository-name: registring-release-demo
          API_TOKEN_GITHUB: ${{ inputs.API_TOKEN_GITHUB }}